language: node_js
node_js:
  - "8"
install:
  - npm install
  - npm install -g firebase-tools
script:
  - npm run lint
  - npm run build:prod
after_success:
  - firebase deploy - project hack-chicago-2018 - token $FIREBASE_TOKEN.
