language: node_js
node_js:
  - "8"
install:
  - npm install
  - npm install -g firebase-tools
script:
  - npm run build:prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "hack-chicago-2018"
